protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	public function actionIncidencias()
	{
		$this->render('incidencias');
	}

	public function actionAnteriores()
	{
		$this->render('anteriores');
	}

	public function actionPendientes()
	{
		$this->render('pendientes');
	}

	public function actionReportes()
	{
		$modelo = new incidencias;

		if(isset($_POST['botonReportes']))
        {
        	$id_usuario =  Yii::app()->user->id;

        	$titulo = $_POST['incidencias']['titulo'];

        	$descripcion = $_POST['incidencias']['descripcion'];

			$conexion = new CDbConnection("mysql:host=localhost;dbname=usuariocruge","root","CRVCLJ");
			$conexion->active = true;

			$sql = "SELECT CURDATE()";
			$instruccion = $conexion->createCommand($sql);
			$resultado = $instruccion->query();
			
			while(($fila = $resultado -> read()) !== false) {
				$fecha= $fila['CURDATE()'];
			}

			$sql = "SELECT CURTIME()";
			$instruccion = $conexion->createCommand($sql);
			$resultado = $instruccion->query();
			
			while(($fila = $resultado -> read()) !== false) {
				$hora= $fila['CURTIME()'];
			}

			$conexion->active = false;

			$area = $_POST['incidencias']['area'];

			$sql = "INSERT INTO incidencias(id_usuario,titulo,descripcion,fecha,hora,area,estatus) VALUES ('" . $id_usuario . "','" . $titulo ."','" . $descripcion . "','" . $fecha . "','" . $hora ."','" . $area ."','Nueva')";

			$instruccion = $conexion->createCommand($sql);
			$resultado = $instruccion->query();


        	Yii::app()->user->setFlash('reportes','Gracias por el reporte, será contactado tan pronto como sea posible.');
			$this->refresh();
        }
        else
        {
			$this->render('reportes',array(
        		'model'=>$modelo, 
    		));
		}
	}

	public function actionVerreportes()
	{
		$modelo = new incidencias;

		if(isset($_POST['botonAceptar']))
        {
        	$id_usuario =  Yii::app()->user->id;

        	$id_incidencia = $_POST['incidencias']['id_incidencia'];
        	$comentarios = $_POST['incidencias']['comentarios'];
        	$id_empleado = $_POST['incidencias']['empleado'];

			$conexion = new CDbConnection("mysql:host=localhost;dbname=usuariocruge","root","CRVCLJ");
			$conexion->active = true;

			$sql = "UPDATE incidencias SET comentarios='" . $comentarios . "',estatus='Pendiente',id_empleado='" . $id_empleado ."' WHERE id_incidencia=' " . $id_incidencia . "'";
			$instruccion = $conexion->createCommand($sql);
			$resultado = $instruccion->execute();

			$this->render('verreportes',array(
        		'model'=>$modelo, 
    		));
        }
        else
        {
			$this->render('verreportes',array(
        		'model'=>$modelo, 
    		));
		}
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'Acerca de', 'url'=>array('/site/page', 'view'=>'about')),
				array('label'=>'Contacto', 'url'=>array('/site/contact')),
				array('label'=>'Login', 'url'=>array('/cruge/ui/login'), 'visible'=>Yii::app()->user->isGuest),
				/*array('label'=>'Administrar usuarios', 'url'=>array('/usuario')),*/
				array('label'=>'Administrar usuarios', 'url'=>Yii::app()->user->ui->userManagementAdminUrl, 'visible'=>Yii::app()->user->getName()=='admin'),
				array('label'=>'Reportar incidencias', 'url'=>array('/site/reportes'), 'visible'=>!Yii::app()->user->isGuest && Yii::app()->user->checkAccess('action_site_reportes') && Yii::app()->user->getName()!='admin'),
				array('label'=>'Ver incidencias no resueltas', 'url'=>array('/site/pendientes'), 'visible'=>!Yii::app()->user->isGuest && Yii::app()->user->checkAccess('action_site_pendientes') && Yii::app()->user->getName()!='admin'),
				array('label'=>'Ver incidencias anteriores', 'url'=>array('/site/anteriores'), 'visible'=>!Yii::app()->user->isGuest && Yii::app()->user->checkAccess('action_site_anteriores') && Yii::app()->user->getName()!='admin'),
				array('label'=>'Incidencias nuevas', 'url'=>$this->createUrl('site/verreportes',array('id'=>'0')), 'visible'=>!Yii::app()->user->isGuest && Yii::app()->user->checkAccess('action_site_verreportes')),
				array('label'=>'Ver todas las incidencias', 'url'=>array('/site/incidencias'), 'visible'=>!Yii::app()->user->isGuest && Yii::app()->user->checkAccess('action_site_incidencias')),
				array('label'=>'Salir ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->


	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->
 <!--<?php echo Yii::app()->user->ui->displayErrorConsole(); ?>-->
</body>
</html>